#!/bin/zsh

# Personal
export DOCS="/Users/ethan/Documents"
export PROJECTS_HOME="$DOCS/proyectos"
export PATH="$DOCS/notas/:$PATH"

# Aliases 
alias makepass='curl -X GET -G https://www.random.org/passwords/ \
	-d "num=1" \
	-d "len=24" \
	-d "format=plain" \
	-d "rnd=new" | pbcopy'

# Vim
export VIM_CONFIG="/Users/ethan/.config/.vim"

# GNU Utils
export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

# Texlive
export PATH="/usr/local/texlive/2020/bin/x86_64-darwin/:$PATH"

# Racket
export PATH="/Applications/Racket v7.9/bin/:$PATH"

# Ruby
export PATH="/usr/local/opt/ruby/bin:$PATH"

# Dotnet BS
export DOTNET_CLI_TELEMETRY_OPTOUT=1
